### ISSUE TITLE
Set cookie is not encoded properly

### ISSUE THREAD

**Issue by Lavoaster** [hex7c0/cookie-encryption#1]
Hey There,

It seems as if the writer is not writing the cookie correctly, or rather it's not correcting encoding the output. I get the following as the cookie value 
```
�|)�G}&�y���(�+�t-4`�Y��k�1aR�x���Xd
�]��L�wpF/nzELixPXNBP+AOSwGA==
```

I'm currently using express as the server, and since I'm using the following methods to setup this library and write the cookie.

Dependency setup:
```
var cookiee = require('cookie-encryption');
var vault = cookiee('test', {
    cipher: 'aes-256-cbc',
    encoding: 'base64',
    cookie: 'oauth-secrets',
    httpOnly: true,
});
```

Writing cookie:
```
vault.write('{"access_token":"yKIWXHFrtHqR27grmWR3qOOW17HykVZlZMa3wJ3a","token_type":"Bearer","expires_in":3600}');
res.status(200).send('done');
```
(Not that it needs mentioning, access token doesn't link to anything that's live)

For what it's worth, I'm when setting the cookie manually, the read method works fine.
```
var text = '{"access_token":"yKIWXHFrtHqR27grmWR3qOOW17HykVZlZMa3wJ3a","token_type":"Bearer","expires_in":3600}';

var cipher = crypto.createCipher('aes-256-cbc', 'test');
var crypted = cipher.update(text,'utf8','base64');
crypted += cipher.final('base64');

res.cookie('oauth-secrets', crypted, {maxAge: 900000, httpOnly: true});

res.status(200).send('done');
```

**Comment by Lavoaster** [comment]
Unrelated: Your `http://supergiovane.tk` domain that is linked in almost all of your sites seems to be in one of those dodgy ad networks that redirect it to a different site every time you visit it.

**Comment by hex7c0** [comment]
hi sorry for delay,
I'll fix this bug immediately

**Comment by hex7c0** [comment]
Unrelated: `http://supergiovane.tk` is no longer a my domain. I'll change all my repos
thanks for the advice!

**Comment by Lavoaster** [comment]
No problem and thanks for the fast fix :heart:
